
export const SET_ALL_POKEMONS = "SET_ALL_POKEMONS";
export const FETCH_ALL_POKEMONS_FAILED = "FETCH_ALL_POKEMONS_FAILED";
export const GET_SEARCHED_NAME = "GET_SEARCHED_NAME";
export const GET_POKEMON_DETAILS= "GET_POKEMON_DETAILS";